### PR TITLE
Add bootstrapping in Massa

### PR DESCRIPTION
**Pull request by aoudiamoncef**

### CODE REVIEW

**Review by damip — APPROVED** [review]

**Comment by aoudiamoncef** [comment]
cc @qdrn

**Comment by qdrn** [comment]
Honestly I'm not found of these pages that mix high level information (explain security model of bootstrap) and very technical ones (edit config files).

**Comment by damip** [comment]
Let's try to unblock this.

@qdrn from what I understand you don't like the fact that the "technical details" part is present at the end of the same document, is that it ? If so, do you think it should be split apart into a separate page ? where would you put it (it concerns node runners) ?

**Comment by damip** [comment]
OK maybe let's move forward by merging this (there is demand in the community) and we will improve it as a followup with more precise feedback

**Comment by qdrn** [comment]
There are issues in this PR (1To instead of 10To).

**Pull request merged**
