### PR TITLE
Update DeWeb CLI docs

### PR DESCRIPTION
**Pull request by pivilartisant**
We are updating DeWeb CLI docs

### CODE REVIEW

**Comment by SlnPons** [comment]
@pivilartisant just a naive question: have you created a `--help` or any other cmd that list all the available functions on the deweb?

**Review by SlnPons — APPROVED** [review]

**Comment by pivilartisant** [comment]
> @pivilartisant just a naive question: have you created a `--help` or any other cmd that list all the available functions on the deweb?

yess ideed ! is it worth adding it to the docs ?

**Comment by SlnPons** [comment]
> > @pivilartisant just a naive question: have you created a `--help` or any other cmd that list all the available functions on the deweb?
> 
> yess ideed ! is it worth adding it to the docs ?

I would say yes so people have a little help at anytime. But I'm not a dev. So I'm not sure it's relevant. Let's wait for @thomas-senechal to review the doc.

**Review by thomas-senechal — COMMENTED** [review]
Sorry, I couldn't comment on lines that were not changed so here is a global comment of all the things I would change:
- There are still some mentions of the `yaml` config file (for example line 33)

- `--wallet_nickname` has been replaced by:
```
 -w, --wallet <path>                Path to the wallet file
 -p, --password <password>          Password for the wallet file
```
IMO we need to explain that ATM only `yaml` format is supported and how to get it (redirect to MW doc https://docs.massa.net/docs/massaStation/massa-wallet/account-backup and tell to use backup as yaml)

- We need to explain the possibility to use the secret key in a better way and give the env variable name `SECRET_KEY` somewhere 
- Examples should be updated to reflect the wallet handle changes (for example, like 99 we use the `-w` of previous version)
- `edit` command has been merged with `upload`
- Other commands we added such as `ls` and `show` can be ignored for now, but maybe we should rewrite a bit this section to only explain how to upload/edit a website and not how to delete and configure the CLI ? And so, have another section that gives details like the config file, all global options, etc ?

**Pull request merged**
